version: '3'
services:
  app:
    build: ./infra/app
    volumes:
      - ./:/var/www
  web:
    build: ./infra/web
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
    links:
      - app
  mysql:
    build: ./infra/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/mysql-data:/var/lib/mysql
      - ./infra/mysql/sqls:/docker-entrypoint-initdb.d
      - ./infra/mysql/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
